name: CD

on: 
  push:
    branches: 
      - release

jobs:
  web:
    
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        
      - name: Launch flutter tests
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.2'
          channel: 'dev'
      - run: flutter test --coverage
        
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
          
      - name: Build for web
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.2'
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter build web
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Build apk
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.2'
          channel: 'dev'
      - run: flutter build apk

      - name: Firebase apk distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: Default
          file: ./build/app/outputs/apk/release/app-release.apk

